keycloak:
  auth-server-url: http://localhost:8007/auth
  realm: ayc
  resource: ayc-user-service

security:
  cors:
    origins: http://localhost:4200

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ayc

